### ISSUE TITLE
Cuidando al ejército norteamericano con ReactJS & Leaflet

### ISSUE THREAD

**Issue by maxenz** [ReactJS-BA/charlas#5]
## Título  :loudspeaker:
Cuidando al ejército norteamericano con ReactJS & Leaflet.

## Descripción (corta) :pencil2:
Presentaremos un caso real de una aplicación de geolocalización de personas y camiones, utilizada por el ejército y gobierno estadounidense, donde vamos a explicar como lo logramos utilizando ReactJS, Redux & LeafletJS. También vamos a charlar de como los middlewares pueden ser una buena solución para hacer código más limpio, y los peligros de usarlos.

## Duración  :hourglass:
_Seleccioná más de una opción si tu charla puede tener diferentes duraciones._
- [ ] 40/50 minutos (única charla del meetup)
- [x] 20/30 minutos (dando lugar a otra charla ese día)
- [ ] 5/10 minutos (lightning talk ⚡)

## Sobre tí  :memo:
Somos dos frontend devs a cargo de este gigantesco proyecto para una startup norteamericana.

- Twitter:_ [@maxoracing](https://twitter.com/maxoracing)
- GitHub: [maxenz](https://github.com/maxenz) & [franciscok](https://github.com/franciscok)
- Sitio web:
- Blog:
- Otro:

## Más detalles que quieras compartir
_Aqui puedes agregar más información sobre tu charla, requerimientos especiales, o lo que quieras._

## Recursos :books:
*Coloca todos los recursos con los que cuentas para tú charla, slides, archivo compartido, repositorio, enlace en youtube, sitio web etc.*

**Comment by CarlosManotas** [comment]
@maxenz hola saludos!, crees poder dar esta charla para noviembre??

**Comment by maxenz** [comment]
Que tal Carlos, que fecha de noviembre? Entre el 16 y el 24 voy a estar de viaje, pero calculo que en otra fecha podemos dar con francisco la charla.

**Comment by CarlosManotas** [comment]
@maxenz hola saludos!, por algun error de comunicación salio la meetup para el 10 de diciembre, con la charla de uds ya publicada, estan listo como para darla ese dia??

**Comment by maxenz** [comment]
Que haces Carlos. El material mas o menos lo tenemos, así que la podemos armar para ese día. Mi consulta es, además de preparar la charla, que otras cosas tenemos que tener en cuenta? Tiempo de charla, comprar morfi o bebida, recursos que vamos a tener ahi para poder grabar la charla, etc?

**Comment by CarlosManotas** [comment]
Segun lo marcado aqui tienes hasta 40/50 minutos de charla, en cuanto al morfi y bebida eso ya lo cuadramos nosotros, al igual que grabar el material de la charla.

**Comment by CarlosManotas** [comment]
@maxenz me puedes confirmar que esta todo ok para el lunes? y si necesitas alguna info para ese dia?

**Comment by maxenz** [comment]
Carlos, todo ok. Estamos terminando de armar la presentación. A que hora necesitarías que estemos ahí? Llevamos nosotros mac para presentar o usamos lo que tengan ahí?

**Comment by CarlosManotas** [comment]
este es el link de la publicación por si no la tenian
https://www.meetup.com/es/React-js-en-Buenos-Aires/events/256804777/
si pueden estar a las 18:00hs para probar que todo ande bien mejor, si llevan sus equipos estaran mas comodos

**Comment by CarlosManotas** [comment]
@maxenz me pasas tu email, hay una info que tengo que darte.

**Comment by maxenz** [comment]
maximilianopoggio@gmail.com

**Comment by nanovazquez** [comment]
Done! Charla de Diciembre 2018 🚀
