### ISSUE TITLE
Hello React Word! (Por Acámica)

### ISSUE THREAD

**Issue by amoritan** [ReactJS-BA/charlas#7]
## Título  :loudspeaker:
__Hello React Word!__ _Aprendiendo React desde cero_

## Descripción (corta) :pencil2:
En Acámica venimos trabajando hace meses en nuestra nueva carrera de __Desarrollo Front-end avanzado en React__ y con motivo del lanzamiento oficial queremos compartir esa experiencia y sus resultados con la comunidad.

La charla consistirá en una introducción a los principales conceptos de React y el paradigma de desarrollo de UI a través de componentes/estados, con contenido original y demostraciones de código en vivo.
Está orientada a web devs de distintas disciplinas que quieran dar sus primeros pasos en React.

## Duración  :hourglass:
- [x] 40/50 minutos (única charla del meetup)
- [ ] 20/30 minutos (dando lugar a otra charla ese día)
- [ ] 5/10 minutos (lightning talk)

## Sobre tí  :memo:
Mi nombre es __Andres Moritan__ y soy desarrollador de contenidos en Acámica, a cargo de la creación de la carrera de __Desarrollo Front-end avanzado en React__. Soy un apasionado por la tecnología con más de 10 años de experiencia en el desarrollo de productos digitales web y mobile.

- Twitter: [@andresmoritan](https://twitter.com/andresmoritan)
- GitHub: [andresmoritan](https://github.com/andresmoritan)
- Sitio web: [www.andresmoritan.com](https://www.andresmoritan.com/#/)

## Más detalles que quieras compartir
En Acámica inspiramos pasión por aprender, explora carreras innovadoras creadas con gigantes de la industria tecnológica en [www.acamica.com](https://www.acamica.com).

**Comment by nanovazquez** [comment]
Done! Charla de Diciembre 2018 🚀
